### ISSUE TITLE
按照腾讯云社区的教程操作后无法同步coding，所以想向您请教一下

### ISSUE THREAD

**Issue by nsv2051** [shenweiyan/GitHub-SYNC#1]
这是报错截图
![Snipaste_2022-02-09_10-05-21](https://user-images.githubusercontent.com/39900381/153108514-87fae09f-3f90-4101-991b-5579c11cddbc.png)

**Comment by shenweiyan** [comment]
1. 你把你的 `${CODING_USERNAME}` 和 `${CODING_PASSWORD}` 都换成真实的值，在命令行下 `git clone` 试一下会不会报错；
2. 如果 1 不报错，检查一下你的 `CODING_USERNAME` 和 `CODING_PASSWORD` 参数有没有可能存在值写错的问题。

**Comment by nsv2051** [comment]
![image](https://user-images.githubusercontent.com/39900381/153321581-02d77189-b943-439e-a9bd-7796e7ff856f.png)
账号和密码也重置了，在命令行下执行也有报错，我感觉是我的coding仓库地址拼接有问题

**Comment by nsv2051** [comment]
问题解决了，原因在于coding账号中的“@”符号没有转码，转码后执行成功了，打扰您了
